### ISSUE TITLE
Certain rows in MsAccess DB are not read and processed

### ISSUE THREAD

**Issue by edwinmyp88** [edwinmyp88/accessdbdataingestor#1]
Refer to screenshot

![image](https://user-images.githubusercontent.com/85217548/192507673-5f2e15c9-e6ec-46d8-afdc-536f6afb8f98.png)

**Comment by tanhanweiii** [comment]
This is because the read.py is get local date (GMT +8) to retrieve today data, but the data from MS Access DB is used GMT, so it will missing the data from (GMT) 16:00 until 23:59 due to local date already is new date.

Now this issue is fixed by modify read.py to get GMT date instead of GMT+8 date.
